name: 'capstone_sales_customer_analytics'
version: '1.0.0'
config-version: 2 

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  capstone_sales_customer_analytics:
    staging:
      +materialized: incremental
      +schema: BRONZE
    silver:
      +materialized: view
      +schema: SILVER
    marts:
      core:
        +materialized: table
        +schema: gold
      reporting:
        +materialized: view
        +schema: gold
  elementary:
    +schema: elementary

on-run-end:
  - "{{ elementary.upload_dbt_artifacts() }}"